apiVersion: netclab.dev/v1alpha1
kind: CliConfig
metadata:
  name: ceos01-cliconfig
spec:
  endpoint: ceos01.default.svc.cluster.local
  revision: 1
  configMapRef:
    name: ceos01-cm
    namespace: default
